// Code generated by MockGen. DO NOT EDIT.
// Source: ./api/utils/tlsvalidator/interface.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// ValidateTLSCertificate mocks base method.
func (m *MockInterface) ValidateTLSCertificate(certBytes, keyBytes []byte, dnsName string) (bool, []string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateTLSCertificate", certBytes, keyBytes, dnsName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].([]string)
	return ret0, ret1
}

// ValidateTLSCertificate indicates an expected call of ValidateTLSCertificate.
func (mr *MockInterfaceMockRecorder) ValidateTLSCertificate(certBytes, keyBytes, dnsName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateTLSCertificate", reflect.TypeOf((*MockInterface)(nil).ValidateTLSCertificate), certBytes, keyBytes, dnsName)
}

// ValidateTLSKey mocks base method.
func (m *MockInterface) ValidateTLSKey(keyBytes []byte) (bool, []string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateTLSKey", keyBytes)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].([]string)
	return ret0, ret1
}

// ValidateTLSKey indicates an expected call of ValidateTLSKey.
func (mr *MockInterfaceMockRecorder) ValidateTLSKey(keyBytes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateTLSKey", reflect.TypeOf((*MockInterface)(nil).ValidateTLSKey), keyBytes)
}
