### REMOVE IN DOCKERFILE
[[constraint]]
  name = "github.com/statoil/radix-operator"
  branch = "master"
### END REMOVE
[[constraint]]
  name = "k8s.io/client-go"
  version = "8.0.0"

[[constraint]] # dep client-go 
  name = "k8s.io/apimachinery"
  revision = "488889b0007f63ffee90b66a34a2deca9ec58774"

[[constraint]] # dep client-go apimachinery 
  name = "github.com/stretchr/testify"
  revision = "c679ae2cc0cb27ec3293fea7e254e47386f05d69"

[[override]] # dep client-go
  name = "github.com/Azure/go-autorest"
  revision = "1ff28809256a84bb6966640ff3d0371af82ccba4"

[[override]] # dep apimachinery
  name = "github.com/json-iterator/go"
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"

[[override]] # dep code-generator
  name = "k8s.io/gengo"
  revision = "01a732e01d00cb9a81bb0ca050d3e6d2b947927b"

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.6"