apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-api
spec:
  build:
    useBuildKit: true
  environments:
    - name: prod
      build:
        from: release
    - name: qa
      build:
        from: master
  components:
    - name: "server"
      readOnlyFileSystem: true
      src: "."
      dockerfileName: "Dockerfile"
      ports:
        - name: http
          port: 3002
        - name: metrics
          port: 9090
      publicPort: http
      runtime:
        architecture: arm64
      monitoring: true
      monitoringConfig:
        portName: metrics
      variables:
        REQUIRE_APP_CONFIGURATION_ITEM: "true"
        REQUIRE_APP_AD_GROUPS: "true"
        USE_PROFILER: "false"
        LOG_LEVEL: info
        LOG_PRETTY: "false"
        PROMETHEUS_URL: http://prometheus-operator-prometheus.monitor.svc.cluster.local:9090
        OIDC_AZURE_AUDIENCE: 6dae42f8-4368-4678-94ff-3960e28e3630
        OIDC_AZURE_ISSUER: https://sts.windows.net/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/
        OIDC_KUBERNETES_ISSUER: ""
        OIDC_KUBERNETES_AUDIENCE: ""
      environmentConfig:
        - environment: qa
          horizontalScaling:
            maxReplicas: 1
            minReplicas: 0
            triggers:
              - name: cron
                cron:
                  timezone: Europe/Oslo
                  start: 0 7 * * 1-5 # 07:00 Monday - Friday
                  end: 0 17 * * 1-5 # 17:00 Monday - Friday
                  desiredReplicas: 1
          resources:
            requests:
              cpu: "50m"
              memory: "100M"
            limits:
              cpu: "200m"
              memory: "400Mi"
          variables:
            GOMAXPROCS: "1"
        - environment: prod
          replicas: 2
          resources:
            requests:
              cpu: "200m"
              memory: "300M"
            limits:
              cpu: "500m"
              memory: "500M"
          variables:
            GOMAXPROCS: "2"
