apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-api
spec:
  environments:
  - name: prod
  - name: qa
    build:
      from: master
  - name: feat-240
    build:
      from: OR-240_RefactorSwaggerContracts
  components:
  - name: "server"
    src: "."
    replicas: 2
    dockerfileName: "Dockerfile"
    ports:
    - name: http
      port: 3002
    public: true
    environmentVariables:
    - environment: qa
      variables:
        PIPELINE_IMG_TAG: "latest"
    - environment: prod
      variables:
        PIPELINE_IMG_TAG: "prod"
    build-secrets:
    - DEPLOY_KEY_OPERATOR
