apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-api
spec:
  build:
    useBuildKit: true
  environments:
    - name: prod
      build:
        from: release
    - name: qa
      build:
        from: master
  components:
    - name: "server"
      readOnlyFileSystem: true
      src: "."
      dockerfileName: "Dockerfile"
      ports:
        - name: http
          port: 3002
        - name: metrics
          port: 9090
      publicPort: http
      monitoring: true
      monitoringConfig:
        portName: metrics
      variables:
        REQUIRE_APP_CONFIGURATION_ITEM: "true"
        REQUIRE_APP_AD_GROUPS: "true"
        USE_PROFILER: "false"
        LOG_LEVEL: info
        LOG_PRETTY: "false"
      environmentConfig:
        - environment: qa
          horizontalScaling:
            minReplicas: 1
            maxReplicas: 2
          resources:
            requests:
              cpu: "50m"
              memory: "100M"
            limits:
              cpu: "200m"
              memory: "200M"
          variables:
            PIPELINE_IMG_TAG: "master-latest"
            TEKTON_IMG_TAG: "main-latest"
            GOMAXPROCS: "1"
        - environment: prod
          replicas: 2
          resources:
            requests:
              cpu: "200m"
              memory: "300M"
            limits:
              cpu: "500m"
              memory: "500M"
          variables:
            PIPELINE_IMG_TAG: "release-latest"
            TEKTON_IMG_TAG: "release-latest"
            GOMAXPROCS: "2"
