apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-api
spec:
  environments:
  - name: prod
    build:
      from: release
  - name: qa
    build:
      from: master
  - name: dev
  components:
  - name: "server"
    src: "."
    dockerfileName: "Dockerfile"
    ports:
    - name: http
      port: 3002
    public: true
    environmentConfig:
    - environment: qa
      horizontalScaling:
        minReplicas: 1
        maxReplicas: 2
      monitoring: true
      resources:
        requests:
          memory: "100M"
          cpu: "50m"
        limits:
          memory: "250M"
          cpu: "500m"
      variables:
        PIPELINE_IMG_TAG: "master-latest"
    - environment: prod
      horizontalScaling:
        minReplicas: 1
        maxReplicas: 5
      monitoring: true
      resources:
        requests:
          memory: "200M"
          cpu: "100m"
        limits:
          memory: "500M"
          cpu: "1000m"
      variables:
        PIPELINE_IMG_TAG: "release-latest"
