// Code generated by MockGen. DO NOT EDIT.
// Source: ./api/utils/tlsvalidation/interface.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockValidator is a mock of Validator interface.
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
}

// MockValidatorMockRecorder is the mock recorder for MockValidator.
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance.
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &MockValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	return m.recorder
}

// ValidatePrivateKey mocks base method.
func (m *MockValidator) ValidatePrivateKey(keyBytes []byte) (bool, []string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatePrivateKey", keyBytes)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].([]string)
	return ret0, ret1
}

// ValidatePrivateKey indicates an expected call of ValidatePrivateKey.
func (mr *MockValidatorMockRecorder) ValidatePrivateKey(keyBytes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePrivateKey", reflect.TypeOf((*MockValidator)(nil).ValidatePrivateKey), keyBytes)
}

// ValidateX509Certificate mocks base method.
func (m *MockValidator) ValidateX509Certificate(certBytes, keyBytes []byte, dnsName string) (bool, []string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateX509Certificate", certBytes, keyBytes, dnsName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].([]string)
	return ret0, ret1
}

// ValidateX509Certificate indicates an expected call of ValidateX509Certificate.
func (mr *MockValidatorMockRecorder) ValidateX509Certificate(certBytes, keyBytes, dnsName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateX509Certificate", reflect.TypeOf((*MockValidator)(nil).ValidateX509Certificate), certBytes, keyBytes, dnsName)
}
