name: radix-api-pr
on:
  pull_request:
    branches:
    - master
jobs:

  build:
    env:	
      GOPATH: /home/runner/work/radix-api/go
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.11
      uses: actions/setup-go@v1
      with:
        go-version: 1.11
      id: go

    - name: Add $GOPATH/bin
      run: |
        echo ::add-path::$(go env GOPATH)/bin

    - name: Check out code into the Go path directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        path: go/src/github.com/equinor/radix-api

    - name: Get dependencies
      run: |    
        go get -u github.com/golang/dep/cmd/dep
        dep ensure -vendor-only

    - name: Generate swagger
      run: |
        export GOBIN=$GOPATH/bin
        go get -u github.com/rakyll/statik
        # Install official release of swagger
        export download_url=$(curl -s https://api.github.com/repos/go-swagger/go-swagger/releases/16311033 | \
        jq -r '.assets[] | select(.name | contains("'"$(uname | tr '[:upper:]' '[:lower:]')"'_amd64")) | .browser_download_url')
        curl -o $GOBIN/swagger -L'#' "$download_url"
        chmod +x $GOBIN/swagger
        make swagger

    - name: Linting
      run: |
        go get -u golang.org/x/lint/golint
        golint `go list ./...`

    - name: Testing
      run: |
        CGO_ENABLED=0 GOOS=linux go test ./...

    - name: Building
      run: |
        CGO_ENABLED=0 GOOS=linux go build -ldflags "-s -w" -a
