name: radix-api-pr
on:
  pull_request:
    branches:
    - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        path: go/src/github.com/equinor/radix-api

    - name: Get dependencies
      run: |        
        go get -u github.com/golang/dep/cmd/dep
        dep ensure -vendor-only
        
    - name: Linting
      run: |
        golint `go list ./...`
      
    - name: Vetting
      run: |
        go vet `go list ./...`

    - name: Testing
      run: |
        CGO_ENABLED=0 GOOS=linux go test ./...

    - name: Building
      run: |        
        CGO_ENABLED=0 GOOS=linux go build -ldflags "-s -w" -a
