name: radix-api-pr
on:
  pull_request:
    branches:
    - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: build docker image
      uses: docker
      run: docker build -t radix-api .
